# DO-NOT-EDIT: Generated by github:vic/flake-file for unflake.
# To re-generate use:   nix-shell . -A unflake.env --run write-inputs
{
  flake-file.url = "github:vic/flake-file";
  import-tree.url = "github:vic/import-tree";
  nixpkgs.url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz";
}
