# @generated by https://codeberg.org/goldstein/unflake
let
  deps = rec {
    unflake_github_vic_flake-file = builtins.fetchTree {
      type = "github";
      owner = "vic";
      repo = "flake-file";
      rev = "982bec8f58dc56360df4dbb246f9d3b846e89dfa";
      lastModified = 1771017115;
      narHash = "sha256-2Cef4MEBKL8YWe0ZEuEV5U/x4aWz9IM8hrxxiD8X3f4=";
    };
    unflake_github_vic_import-tree = builtins.fetchTree {
      type = "github";
      owner = "vic";
      repo = "import-tree";
      rev = "3c23749d8013ec6daa1d7255057590e9ca726646";
      lastModified = 1763762820;
      narHash = "sha256-ZvYKbFib3AEwiNMLsejb/CWs/OL/srFQ8AogkebEPF0=";
    };
    unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz = builtins.fetchTree {
      type = "tarball";
      url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz";
      lastModified = 1770843696;
      narHash = "sha256-9SFCZkVcpDOV6unH5hVEy4+dB0rxMuUoBnDAO6vshac=";
    };
  };
  universe = rec {
    unflake_github_vic_flake-file = ((import "${deps.unflake_github_vic_flake-file.outPath}/flake.nix").outputs {
      self = unflake_github_vic_flake-file;
    }) // deps.unflake_github_vic_flake-file // {
      _flake = true;
      outPath = "${deps.unflake_github_vic_flake-file.outPath}";
      sourceInfo = deps.unflake_github_vic_flake-file;
    };
    unflake_github_vic_import-tree = ((import "${deps.unflake_github_vic_import-tree.outPath}/flake.nix").outputs {
      self = unflake_github_vic_import-tree;
    }) // deps.unflake_github_vic_import-tree // {
      _flake = true;
      outPath = "${deps.unflake_github_vic_import-tree.outPath}";
      sourceInfo = deps.unflake_github_vic_import-tree;
    };
    unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz = ((import "${deps.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz.outPath}/flake.nix").outputs {
      self = unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz;
    }) // deps.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz // {
      _flake = true;
      outPath = "${deps.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz.outPath}";
      sourceInfo = deps.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz;
    };
  };
  inputs = {
    flake-file = universe.unflake_github_vic_flake-file;
    import-tree = universe.unflake_github_vic_import-tree;
    nixpkgs = universe.unflake_tarball_https---channels-nixos-org-nixpkgs-unstable-nixexprs-tar-xz;
    self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
    withInputs = outputs: let self = outputs (inputs // { inherit self; }); in self;
    __functor = self: self.withInputs;
  };
in inputs