# @generated by https://codeberg.org/goldstein/unflake
let
  indirect_deps = {
  };
  specs = rec {
    unflake_github_denful_flake-file = {
      type = "github";
      owner = "denful";
      repo = "flake-file";
      rev = "04ca28cf570276e70a9a5f694791ab2a60f1f300";
      lastModified = 1777679829;
      narHash = "sha256-zQxY90pq7BDbeimAiOfuK2U0huzo6oHOiC8zEpRgsbQ=";
    };
    unflake_github_denful_import-tree = {
      type = "github";
      owner = "denful";
      repo = "import-tree";
      rev = "c41e7d58045f9057880b0d85e1152d6a4430dbf1";
      lastModified = 1773693634;
      narHash = "sha256-BtZ2dtkBdSUnFPPFc+n0kcMbgaTxzFNPv2iaO326Ffg=";
    };
    unflake_github_denful_with-inputs = {
      type = "github";
      owner = "denful";
      repo = "with-inputs";
      rev = "e8729bdb4afb57fc72c2a7084a77a7ee09c7e38f";
      lastModified = 1777938927;
      narHash = "sha256-efneEYyUSQ7HOg/peGvfotb/P1N1+WWp10P1kMQSpe8=";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "68a8af93ff4297686cb68880845e61e5e2e41d92";
      lastModified = 1778124196;
      narHash = "sha256-pYEytCNic/czazbV9r3tbQ6BZzqRBg/41x2dIC5ymOo=";
    };
    unflake_github_denful_with-inputs_flake_false = unflake_github_denful_with-inputs;
  };
  deps = indirect_deps // builtins.mapAttrs (_: spec: builtins.fetchTree spec) specs;
  injections = rec {
    unflake_github_denful_flake-file = {
    };
    unflake_github_denful_import-tree = {
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
    };
  };
  inject = name: flake_path: subdir:
    let
      inputs = builtins.mapAttrs (_: dep: universe.${dep}) injections.${name} // {
        inherit self;
      };
      sourceInfo = deps.${name};
      outPath = "${sourceInfo.outPath}${subdir}";
      outputs = (import "${sourceInfo.outPath}/${flake_path}").outputs inputs;
      self = outputs // sourceInfo // {
        inherit inputs outputs outPath sourceInfo;
        _type = "flake";
        _flake = true;
      };
    in self;
  universe = rec {
    unflake_github_denful_flake-file = inject "unflake_github_denful_flake-file" "flake.nix" "";
    unflake_github_denful_import-tree = inject "unflake_github_denful_import-tree" "flake.nix" "";
    unflake_github_denful_with-inputs_flake_false = deps.unflake_github_denful_with-inputs_flake_false;
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable" "flake.nix" "";
  };
  inputs = {
    flake-file = universe.unflake_github_denful_flake-file;
    import-tree = universe.unflake_github_denful_import-tree;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    with-inputs = universe.unflake_github_denful_with-inputs_flake_false;
  };
in inputs // {
  withInputs = fn: let outputs = fn (inputs // { inherit self; }); self = outputs // {
    inherit inputs outputs;
    _type = "flake";
    outPath = builtins.toString ./.;
  }; in self;
  __functor = self: self.withInputs;
  self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
  _unflake = { inherit specs deps injections; };
}
