# @generated by https://codeberg.org/goldstein/unflake
let
  deps = rec {
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "c0f3d81a7ddbc2b1332be0d8481a672b4f6004d6";
      lastModified = 1772173633;
      narHash = "sha256-MOH58F4AIbCkh6qlQcwMycyk5SWvsqnS/TCfnqDlpj4=";
    };
    unflake_github_vic_flake-file = builtins.fetchTree {
      type = "github";
      owner = "vic";
      repo = "flake-file";
      rev = "cdb4abe76b3ff0b611343514f584faa2688a12af";
      lastModified = 1772337812;
      narHash = "sha256-5FB/FQ+gCvFbEuyMxydkUHuMCe0UEgMra5jI2D6SAQU=";
    };
    unflake_github_vic_import-tree = builtins.fetchTree {
      type = "github";
      owner = "vic";
      repo = "import-tree";
      rev = "205675fa599ff8a74b6c8c2cc5149cdaeac76f5f";
      lastModified = 1772263719;
      narHash = "sha256-4TRO+jUycfR3g4KAbyK0wQEEJ7Xcmid2Ry+tWv4HPLw=";
    };
    unflake_github_vic_with-inputs = builtins.fetchTree {
      type = "github";
      owner = "vic";
      repo = "with-inputs";
      rev = "ca62018475be1999e57fbfa7ec14ebea7c6e483d";
      lastModified = 1772342380;
      narHash = "sha256-WFCkvOrArY0rhIPLESqitQHDpl1NFBCK4/7/z6c1040=";
    };
    unflake_github_vic_with-inputs_flake_false = unflake_github_vic_with-inputs;
  };
  universe = rec {
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}/flake.nix").outputs {
      self = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    }) // deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable // {
      _flake = true;
      outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}";
      sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    };
    unflake_github_vic_flake-file = ((import "${deps.unflake_github_vic_flake-file.outPath}/flake.nix").outputs {
      self = unflake_github_vic_flake-file;
    }) // deps.unflake_github_vic_flake-file // {
      _flake = true;
      outPath = "${deps.unflake_github_vic_flake-file.outPath}";
      sourceInfo = deps.unflake_github_vic_flake-file;
    };
    unflake_github_vic_import-tree = ((import "${deps.unflake_github_vic_import-tree.outPath}/flake.nix").outputs {
      self = unflake_github_vic_import-tree;
    }) // deps.unflake_github_vic_import-tree // {
      _flake = true;
      outPath = "${deps.unflake_github_vic_import-tree.outPath}";
      sourceInfo = deps.unflake_github_vic_import-tree;
    };
    unflake_github_vic_with-inputs_flake_false = deps.unflake_github_vic_with-inputs_flake_false;
  };
  inputs = {
    flake-file = universe.unflake_github_vic_flake-file;
    import-tree = universe.unflake_github_vic_import-tree;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    with-inputs = universe.unflake_github_vic_with-inputs_flake_false;
    self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
    withInputs = outputs: let self = outputs (inputs // { inherit self; }); in self;
    __functor = self: self.withInputs;
  };
in inputs